version: '3.8'
x-logging:
    &default-logging
    options:
    max-size: '10m'
    max-file: '1'
    driver: json-file
services:
    portainer:
        image: portainer/portainer
        container_name: portainer
        restart: on-failure
        ports:
            - "9000:9000"
        volumes:
        - /var/run/docker.sock:/var/run/docker.sock
        - ${VOLUMES_DIR}/portainer:/data
        logging: *default-logging 
volumes:
  portainer_data:



